name: nerax_yrion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+35

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Packages premium pour la connexion sécurisée au serveur Render / FastAPI
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0 # 🔑 Gestion locale des sessions Yrion
  image_picker: ^1.2.2
  image_cropper: ^7.0.0 # ✂️ Version mise à niveau pour l'API v2 d'Android (Zéro crash au build)
  
  # 🌐 PACKAGES MESSAGERIE : Architecture Temps Réel Haute Disponibilité (WhatsApp-like)
  web_socket_channel: ^3.0.1 # Canal de communication bidirectionnel persistant
  intl: ^0.19.0 # Horodatage précis des paquets et messages (ex: 21:18)

  # 🎬 CRITIQUE : Requis pour le streaming des Splits vidéos des utilisateurs
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Le package pour générer les icônes sans déformation
  flutter_launcher_icons: ^0.13.1

# Configuration premium de ton icône d'application
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/yrion_logo_premium.png"
  
  # Configuration adaptative Android - Corrigée en noir (#070512) pour coller à ton UI cosmique
  adaptive_icon_background: "#070512"
  adaptive_icon_foreground: "assets/yrion_logo_premium.png"

flutter:
  uses-material-design: true

  # Déclaration du dossier assets pour tes images et logos
  assets:
    - assets/