name: nerax_yrion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Le package magique pour générer les icônes sans déformation
  flutter_launcher_icons: ^0.13.1

# Configuration premium de ton icône d'application
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/yrion_logo_premium.png"
  
  # Configuration adaptative Android pour un centrage parfait sans déformation
  adaptive_icon_background: "#FFFFFF" # Couleur de fond (ici blanc, tu peux changer le code HEX si besoin)
  adaptive_icon_foreground: "assets/yrion_logo_premium.png"

flutter:
  uses-material-design: true

  # Déclaration de ton dossier assets pour pouvoir utiliser toutes tes images dans le code
  assets:
    - assets/